### hello world: run node hello.js --utBus.serviceBus.jsonrpc.port=8090
POST http://localhost:8090/rpc/ports/subject/request
Content-Type: application/json

{
    "id": 1,
    "jsonrpc": "2.0",
    "method": "subject.object.predicate",
    "params": [{}, {}]
}

### api: run node api.js --utBus.serviceBus.jsonrpc.port=8090
POST http://localhost:8090/rpc/subject/object/predicate
Content-Type: application/json

{
    "id": 1,
    "jsonrpc": "2.0",
    "timeout": 1000,
    "method": "subject.object.predicate",
    "params": {}
}

### api gateway: run node gateway.js
POST http://localhost:8080/rpc/subject/object/predicate
Content-Type: application/json

{
    "id": 1,
    "jsonrpc": "2.0",
    "timeout": 1000,
    "method": "subject.object.predicate",
    "params": {}
}
